name: Build Flutter APK

on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'  # Specify the Flutter version or use "latest"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 5: Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
